// İlk kurulumda veritabanı boşsa yüklenen başlangıç verisi: alanlar, masalar
// ve menü. Gerçek veriler tamamen SQLite'ta tutulur; bu sadece "tohum"dur —
// uygulama çalıştıkça masa/menü değişiklikleri kalıcı olarak veritabanına
// yazılır, bu liste bir daha kullanılmaz (tablo zaten doluysa atlanır).

class SeedArea {
  const SeedArea(this.name, this.tableCount);
  final String name;
  final int tableCount;
}

/// Alan adı -> o alandaki masa sayısı. Toplam 40 masa.
const List<SeedArea> seedAreas = [
  SeedArea('Salon', 18),
  SeedArea('Teras', 12),
  SeedArea('Bar', 6),
  SeedArea('Balkon', 4),
];

class SeedMenuItem {
  const SeedMenuItem({
    required this.id,
    required this.name,
    required this.price,
    required this.category,
    required this.stripeA,
    required this.stripeB,
    this.popular = false,
    this.description = '',
    this.tags = const [],
  });

  final String id;
  final String name;
  final int price;
  final String category;
  final bool popular;
  final int stripeA;
  final int stripeB;
  final String description;
  final List<String> tags;
}

/// Sabit kategori sırası (menü ekranındaki sekmeler). 'Popüler' gerçek bir
/// kategori değil, `popular == true` olan ürünleri filtreleyen özel bir
/// sekmedir.
const List<String> menuCategories = [
  'Popüler',
  'Başlangıçlar',
  'Salatalar',
  'Ana Yemekler',
  'Pizza',
  'Tatlılar',
  'İçecekler',
];

const List<SeedMenuItem> seedMenuItems = [
  SeedMenuItem(
    id: 'risotto',
    name: 'Trüflü Mantarlı Risotto',
    price: 420,
    category: 'Ana Yemekler',
    popular: true,
    stripeA: 0xFFE9D9C4,
    stripeB: 0xFFEFE4D3,
    description:
        'Arborio pirinç, karışık mantar, parmesan ve siyah trüf yağı ile '
        'hazırlanmıştır. Taze fesleğen ile servis edilir.',
    tags: ['Vejetaryen', 'Glutensiz Seçenek'],
  ),
  SeedMenuItem(
    id: 'somon',
    name: 'Izgara Somon',
    price: 510,
    category: 'Ana Yemekler',
    popular: true,
    stripeA: 0xFFD9C6D4,
    stripeB: 0xFFE6D9E1,
    description:
        'Taze somon fileto, mevsim sebzeleri ve limonlu tereyağı sos ile '
        'ızgarada pişirilir.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'kofte',
    name: 'Köz Patlıcan Salçalı Köfte',
    price: 365,
    category: 'Ana Yemekler',
    stripeA: 0xFFD9C7BE,
    stripeB: 0xFFE6DBD3,
    description:
        'Izgara köfte, köz patlıcan salçası ve tereyağlı pilav ile servis '
        'edilir.',
  ),
  SeedMenuItem(
    id: 'tavuk-sis',
    name: 'Tavuk Şiş',
    price: 340,
    category: 'Ana Yemekler',
    stripeA: 0xFFE3D8C2,
    stripeB: 0xFFEEE6D6,
    description: 'Marine edilmiş tavuk göğsü, közlenmiş biber ve bulgur pilavı ile.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'kuzu-tandir',
    name: 'Kuzu Tandır',
    price: 560,
    category: 'Ana Yemekler',
    stripeA: 0xFFD8C4BE,
    stripeB: 0xFFE7D9D3,
    description: 'Fırında uzun süre pişirilmiş kuzu but, közlenmiş sebzeler ile.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'levrek-bugulama',
    name: 'Levrek Buğulama',
    price: 495,
    category: 'Ana Yemekler',
    stripeA: 0xFFD3DEDA,
    stripeB: 0xFFE4ECE9,
    description: 'Fırında sebzeli buğulama levrek fileto, zeytinyağı ve limon ile.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'dana-biftek',
    name: 'Izgara Dana Biftek',
    price: 620,
    category: 'Ana Yemekler',
    popular: true,
    stripeA: 0xFFD2B9AE,
    stripeB: 0xFFE3CFC6,
    description: 'Izgara dana biftek, közlenmiş sebzeler ve kırmızı şarap sos ile.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'hunkarbegendi',
    name: 'Hünkar Beğendi',
    price: 395,
    category: 'Ana Yemekler',
    stripeA: 0xFFDDCBBC,
    stripeB: 0xFFEBDDD1,
    description: 'Kuşbaşı dana, közlenmiş patlıcan beğendi üzerinde servis edilir.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'mantı',
    name: 'Ev Yapımı Mantı',
    price: 285,
    category: 'Ana Yemekler',
    stripeA: 0xFFE4D7BE,
    stripeB: 0xFFF0E7D3,
    description: 'El açması mantı, yoğurtlu ve tereyağlı sos, nane ve pul biber ile.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'tavuk-kanat',
    name: 'Barbekü Tavuk Kanat',
    price: 265,
    category: 'Ana Yemekler',
    stripeA: 0xFFDFC3AC,
    stripeB: 0xFFEDD9C6,
    description: 'Barbekü soslu fırın tavuk kanat, çıtır patates eşliğinde.',
  ),
  SeedMenuItem(
    id: 'karides',
    name: 'Karides Güveç',
    price: 480,
    category: 'Başlangıçlar',
    popular: true,
    stripeA: 0xFFC9D4C1,
    stripeB: 0xFFDDE4D6,
    description: 'Güveçte sote karides, domates ve kaşar peyniri ile.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'mercimek-corbasi',
    name: 'Mercimek Çorbası',
    price: 140,
    category: 'Başlangıçlar',
    stripeA: 0xFFE3D3B8,
    stripeB: 0xFFEFE4CB,
    description: 'Ev yapımı, tereyağlı ve nane aromalı klasik mercimek çorbası.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'humus',
    name: 'Humus Tabağı',
    price: 165,
    category: 'Başlangıçlar',
    stripeA: 0xFFDCD2BB,
    stripeB: 0xFFEAE3CE,
    description: 'Zeytinyağlı humus, sumak ve taze pide ile servis edilir.',
    tags: ['Vejetaryen', 'Glutensiz Seçenek'],
  ),
  SeedMenuItem(
    id: 'sigara-boregi',
    name: 'Sigara Böreği',
    price: 155,
    category: 'Başlangıçlar',
    stripeA: 0xFFE6DDBF,
    stripeB: 0xFFF0E9D1,
    description: 'Beyaz peynirli, el açması yufka ile kızartılmış sigara böreği (6 adet).',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'ezogelin-corbasi',
    name: 'Ezogelin Çorbası',
    price: 135,
    category: 'Başlangıçlar',
    stripeA: 0xFFE0CBA6,
    stripeB: 0xFFEEDFC0,
    description: 'Kırmızı mercimek, pirinç ve nane ile geleneksel ezogelin çorbası.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'cacik',
    name: 'Cacık',
    price: 120,
    category: 'Başlangıçlar',
    stripeA: 0xFFD9E2D2,
    stripeB: 0xFFE9EFE3,
    description: 'Yoğurt, salatalık, sarımsak ve nane ile serinletici cacık.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'kalamar-tava',
    name: 'Kalamar Tava',
    price: 285,
    category: 'Başlangıçlar',
    stripeA: 0xFFE4D6C0,
    stripeB: 0xFFF0E7D5,
    description: 'Çıtır kalamar halkaları, tartar sos ve limon ile servis edilir.',
  ),
  SeedMenuItem(
    id: 'arnavut-cigeri',
    name: 'Arnavut Ciğeri',
    price: 245,
    category: 'Başlangıçlar',
    stripeA: 0xFFDCC0BA,
    stripeB: 0xFFEAD5D0,
    description: 'Baharatlı kızarmış ciğer, soğan ve sumak salatası eşliğinde.',
    tags: ['Glutensiz'],
  ),
  SeedMenuItem(
    id: 'patates-kizartmasi',
    name: 'Çıtır Patates Kızartması',
    price: 130,
    category: 'Başlangıçlar',
    stripeA: 0xFFE8D8AF,
    stripeB: 0xFFF2E7C6,
    description: 'Kaşarlı veya sade tercih edilebilen çıtır patates kızartması.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'mevsim-salata',
    name: 'Mevsim Salata',
    price: 155,
    category: 'Salatalar',
    stripeA: 0xFFCFDBC4,
    stripeB: 0xFFE0E9D6,
    description: 'Mevsim yeşillikleri, domates, salatalık ve nar ekşili sos ile.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'akdeniz-salata',
    name: 'Akdeniz Salata',
    price: 195,
    category: 'Salatalar',
    popular: true,
    stripeA: 0xFFC9D6C6,
    stripeB: 0xFFDCE6D9,
    description: 'Beyaz peynir, zeytin, roka ve kiraz domates, zeytinyağı sos ile.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'sezar-salata',
    name: 'Tavuklu Sezar Salata',
    price: 235,
    category: 'Salatalar',
    stripeA: 0xFFDDD9BE,
    stripeB: 0xFFEAE7D3,
    description: 'Izgara tavuk, marul, parmesan ve kruton, sezar sos ile.',
  ),
  SeedMenuItem(
    id: 'coban-salata',
    name: 'Çoban Salata',
    price: 140,
    category: 'Salatalar',
    stripeA: 0xFFD3DEC7,
    stripeB: 0xFFE5EDDC,
    description: 'İnce doğranmış domates, salatalık, biber, soğan ve maydanoz.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'margherita',
    name: 'Margherita Pizza',
    price: 310,
    category: 'Pizza',
    popular: true,
    stripeA: 0xFFDCC7B7,
    stripeB: 0xFFEAD9CB,
    description: 'Domates sos, mozzarella ve taze fesleğen ile ince hamur pizza.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'sucuklu-pizza',
    name: 'Sucuklu Pizza',
    price: 350,
    category: 'Pizza',
    stripeA: 0xFFD8BCAE,
    stripeB: 0xFFE8D3C6,
    description: 'Domates sos, mozzarella, sucuk ve közlenmiş biber.',
  ),
  SeedMenuItem(
    id: 'dort-peynirli-pizza',
    name: 'Dört Peynirli Pizza',
    price: 375,
    category: 'Pizza',
    stripeA: 0xFFE6D9B9,
    stripeB: 0xFFF1E9CE,
    description: 'Mozzarella, kaşar, gorgonzola ve parmesan karışımı.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'karisik-pizza',
    name: 'Karışık Pizza',
    price: 385,
    category: 'Pizza',
    popular: true,
    stripeA: 0xFFDBC2AC,
    stripeB: 0xFFEAD8C6,
    description: 'Sucuk, sosis, mantar, biber ve zeytin ile karışık pizza.',
  ),
  SeedMenuItem(
    id: 'biberli-pizza',
    name: 'Acılı Biberli Pizza',
    price: 345,
    category: 'Pizza',
    stripeA: 0xFFDDC0AF,
    stripeB: 0xFFEBD6CA,
    description: 'Acı sucuk, jalapeno ve mozzarella ile baharatlı pizza.',
  ),
  SeedMenuItem(
    id: 'vejeteryan-pizza',
    name: 'Vejeteryan Pizza',
    price: 330,
    category: 'Pizza',
    stripeA: 0xFFD5DFC0,
    stripeB: 0xFFE6EDD6,
    description: 'Mantar, biber, mısır, zeytin ve kırmızı soğan ile.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'baklava',
    name: 'Baklava',
    price: 175,
    category: 'Tatlılar',
    popular: true,
    stripeA: 0xFFE9D6B9,
    stripeB: 0xFFF0E3C8,
    description: 'Fıstıklı el açması baklava, üç dilim.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'sutlac',
    name: 'Fırın Sütlaç',
    price: 130,
    category: 'Tatlılar',
    stripeA: 0xFFEFE7D2,
    stripeB: 0xFFF7F1E4,
    description: 'Fırında kavrulmuş, üzeri karamelize klasik sütlaç.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'kazandibi',
    name: 'Kazandibi',
    price: 145,
    category: 'Tatlılar',
    stripeA: 0xFFE2D3C9,
    stripeB: 0xFFEEE2D8,
    description: 'Hafif karamelize taban ile geleneksel muhallebi tatlısı.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'profiterol',
    name: 'Profiterol',
    price: 165,
    category: 'Tatlılar',
    popular: true,
    stripeA: 0xFFDCC9B9,
    stripeB: 0xFFEBDDD1,
    description: 'Çikolata soslu, krema dolgulu profiterol.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'tiramisu',
    name: 'Tiramisu',
    price: 180,
    category: 'Tatlılar',
    stripeA: 0xFFD9CBBB,
    stripeB: 0xFFE9DFD2,
    description: 'Kahve ve mascarpone katmanlı, kakao tozlu klasik tiramisu.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'kunefe',
    name: 'Künefe',
    price: 190,
    category: 'Tatlılar',
    stripeA: 0xFFE8CE93,
    stripeB: 0xFFF2E3B8,
    description: 'Sıcak servis edilen, peynirli ve şerbetli klasik künefe.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'dondurma',
    name: 'Üç Top Dondurma',
    price: 120,
    category: 'Tatlılar',
    stripeA: 0xFFE9DCC6,
    stripeB: 0xFFF4EDDD,
    description: 'Seçilen üç aromayla servis edilen ev yapımı dondurma.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'ayran',
    name: 'Ayran',
    price: 95,
    category: 'İçecekler',
    stripeA: 0xFFDCE6E0,
    stripeB: 0xFFE8EFEA,
    description: 'Ev yapımı, taze köpüklü ayran.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'kola',
    name: 'Kola',
    price: 90,
    category: 'İçecekler',
    stripeA: 0xFFDCC9C4,
    stripeB: 0xFFE9DAD6,
    description: '33 cl kutu, buzla servis edilir.',
  ),
  SeedMenuItem(
    id: 'portakal-suyu',
    name: 'Taze Sıkılmış Portakal Suyu',
    price: 120,
    category: 'İçecekler',
    stripeA: 0xFFE9CFA6,
    stripeB: 0xFFF2E1C0,
    description: 'Günlük taze sıkım, katkısız portakal suyu.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'turk-kahvesi',
    name: 'Türk Kahvesi',
    price: 110,
    category: 'İçecekler',
    stripeA: 0xFFC9B7A8,
    stripeB: 0xFFDCCFC3,
    description: 'Cezvede pişirilmiş, lokum eşliğinde geleneksel Türk kahvesi.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'limonata',
    name: 'Ev Yapımı Limonata',
    price: 105,
    category: 'İçecekler',
    stripeA: 0xFFE4E4B8,
    stripeB: 0xFFF0F0D2,
    description: 'Taze sıkılmış limon ve nane ile ev yapımı limonata.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'cay',
    name: 'Çay',
    price: 50,
    category: 'İçecekler',
    stripeA: 0xFFDEC0B4,
    stripeB: 0xFFECD8CF,
    description: 'Semaverde demlenmiş, ince belli bardakta servis edilir.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'maden-suyu',
    name: 'Maden Suyu',
    price: 70,
    category: 'İçecekler',
    stripeA: 0xFFD7E1E3,
    stripeB: 0xFFE7EDEE,
    description: '200 ml doğal maden suyu.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
  SeedMenuItem(
    id: 'latte',
    name: 'Sütlü Kahve (Latte)',
    price: 140,
    category: 'İçecekler',
    stripeA: 0xFFD6C5B4,
    stripeB: 0xFFE7DBCE,
    description: 'Espresso ve buharda ısıtılmış süt ile hazırlanan latte.',
    tags: ['Vejetaryen'],
  ),
  SeedMenuItem(
    id: 'ice-tea',
    name: 'Şeftali Buzlu Çay',
    price: 95,
    category: 'İçecekler',
    stripeA: 0xFFE7C9A9,
    stripeB: 0xFFF2DFC4,
    description: 'Buzla servis edilen, şeftali aromalı soğuk çay.',
    tags: ['Vejetaryen', 'Glutensiz'],
  ),
];
